# Generated by Django 5.0.6 on 2024-05-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tree01", "0002_usercase_cheaked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercase",
            old_name="cheaked",
            new_name="checked",
        ),
    ]
