# Generated by Django 5.0.6 on 2024-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree01", "0003_rename_cheaked_usercase_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercase",
            name="actual_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usercase",
            name="user_quantity",
            field=models.IntegerField(choices=[(0, "0"), (1, "1")], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usercase",
            name="tree_type",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
